# .github/workflows/daily_verse.yml
name: Send Daily Bible Verse

on:
  schedule:
    - cron: '0 19 * * *'  # Executa todos os dias às 10h UTC (~7h no Brasil)
  workflow_dispatch:     # Permite execução manual também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_NUMBER: ${{ secrets.TWILIO_WHATSAPP_NUMBER }}
          RECIPIENT_NUMBERS: ${{ secrets.RECIPIENT_NUMBERS }}
        run: python daily_verse.py
